version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "your_password"
      MYSQL_DATABASE: "crud_db"
  web:
#     depends_on:
 #      - db
      build: .
      ports: 
       - "80:5000"
